### ISSUE TITLE
Outdated version of network-config.yaml file deployed on Windows OS

### ISSUE THREAD

**Issue by MBadea17** [oceanprotocol/ocean.py#1308]
Here's the content of the network-config.yaml file deployed by eth-brownie at the installation of the ocean-lib on Windows OS. 

```
live:
  - name: Ethereum
    networks:
      - name: Mainnet (Infura)
        chainid: 1
        id: mainnet
        host: https://mainnet.infura.io/v3/$WEB3_INFURA_PROJECT_ID
        explorer: https://api.etherscan.io/api
      - name: Ropsten (Infura)
        chainid: 3
        id: ropsten
        host: https://ropsten.infura.io/v3/$WEB3_INFURA_PROJECT_ID
        explorer: https://api-ropsten.etherscan.io/api
      - name: Rinkeby (Infura)
        chainid: 4
        id: rinkeby
        host: https://rinkeby.infura.io/v3/$WEB3_INFURA_PROJECT_ID
        explorer: https://api-rinkeby.etherscan.io/api
      - name: Goerli (Infura)
        chainid: 5
        id: goerli
        host: https://goerli.infura.io/v3/$WEB3_INFURA_PROJECT_ID
        explorer: https://api-goerli.etherscan.io/api
      - name: Kovan (Infura)
        chainid: 42
        id: kovan
        host: https://kovan.infura.io/v3/$WEB3_INFURA_PROJECT_ID
        explorer: https://api-kovan.etherscan.io/api
  - name: Ethereum Classic
    networks:
      - name: Mainnet
        chainid: 61
        id: etc
        host: https://www.ethercluster.com/etc
        explorer:  https://blockscout.com/etc/mainnet/api
      - name: Kotti
        chainid: 6
        id: kotti
        host: https://www.ethercluster.com/kotti
        explorer: https://blockscout.com/etc/kotti/api

development:
  - name: Ganache-CLI
    id: development
    cmd: ganache-cli
    host: http://127.0.0.1
    cmd_settings:
      port: 8545
      gas_limit: 6721975
      accounts: 10
      evm_version: istanbul
      mnemonic: brownie
  - name: Ganache-CLI (Mainnet Fork)
    id: mainnet-fork
    cmd: ganache-cli
    host: http://127.0.0.1
    timeout: 120
    cmd_settings:
      port: 8545
      gas_limit: 10000000
      accounts: 10
      evm_version: istanbul
      mnemonic: brownie
      fork: mainnet

```

In contrast, here is the content of network-config.yaml file deployed by eth-brownie at the installation of ocean-lib on Ubuntu Linux:

```
live:
  - name: Ethereum
    networks:
      - name: Mainnet (Infura)
        chainid: 1
        id: mainnet
        host: https://mainnet.infura.io/v3/$WEB3_INFURA_PROJECT_ID
        explorer: https://api.etherscan.io/api
        multicall2: "0x5BA1e12693Dc8F9c48aAD8770482f4739bEeD696"
        provider: infura
      - name: Ropsten (Infura)
        chainid: 3
        id: ropsten
        host: https://ropsten.infura.io/v3/$WEB3_INFURA_PROJECT_ID
        explorer: https://api-ropsten.etherscan.io/api
        multicall2: "0x5BA1e12693Dc8F9c48aAD8770482f4739bEeD696"
        provider: infura
      - name: Rinkeby (Infura)
        chainid: 4
        id: rinkeby
        host: https://rinkeby.infura.io/v3/$WEB3_INFURA_PROJECT_ID
        explorer: https://api-rinkeby.etherscan.io/api
        multicall2: "0x5BA1e12693Dc8F9c48aAD8770482f4739bEeD696"
        provider: infura
      - name: Goerli (Infura)
        chainid: 5
        id: goerli
        host: https://goerli.infura.io/v3/$WEB3_INFURA_PROJECT_ID
        explorer: https://api-goerli.etherscan.io/api
        multicall2: "0x5BA1e12693Dc8F9c48aAD8770482f4739bEeD696"
        provider: infura
      - name: Kovan (Infura)
        chainid: 42
        id: kovan
        host: https://kovan.infura.io/v3/$WEB3_INFURA_PROJECT_ID
        explorer: https://api-kovan.etherscan.io/api
        multicall2: "0x5BA1e12693Dc8F9c48aAD8770482f4739bEeD696"
        provider: infura
  - name: Ethereum Classic
    networks:
      - name: Mainnet
        chainid: 61
        id: etc
        host: https://www.ethercluster.com/etc
        explorer: https://blockscout.com/etc/mainnet/api
      - name: Kotti
        chainid: 6
        id: kotti
        host: https://www.ethercluster.com/kotti
        explorer: https://blockscout.com/etc/kotti/api
  - name: Arbitrum
    networks:
      - name: Mainnet
        chainid: 42161
        id: arbitrum-main
        host: https://arb1.arbitrum.io/rpc
        explorer: https://api.arbiscan.io/api
        multicall2: "0x5B5CFE992AdAC0C9D48E05854B2d91C73a003858"
  - name: Avalanche
    networks:
      - chainid: 43114
        explorer: https://api.snowtrace.io/api
        host: https://api.avax.network/ext/bc/C/rpc
        id: avax-main
        name: Mainnet
      - chainid: 43113
        host: https://api.avax-test.network/ext/bc/C/rpc
        id: avax-test
        name: Testnet
  - name: Aurora
    networks:
      - name: Mainnet
        chainid: 1313161554
        id: aurora-main
        host: https://mainnet.aurora.dev
        explorer: https://api.aurorascan.dev/api
        multicall2: "0xace58a26b8Db90498eF0330fDC9C2655db0C45E2"
      - name: Testnet
        chainid: 1313161555
        id: aurora-test
        host: https://testnet.aurora.dev
        explorer: https://testnet.aurorascan.dev/api
  - name: Binance Smart Chain
    networks:
      - name: Testnet
        chainid: 97
        id: bsc-test
        host: https://data-seed-prebsc-1-s1.binance.org:8545
        explorer: https://api-testnet.bscscan.com/api
      - name: Mainnet
        chainid: 56
        id: bsc-main
        host: https://bsc-dataseed.binance.org
        explorer: https://api.bscscan.com/api
  - name: Boba
    networks:
      - name: Testnet
        chainid: 28
        id: boba-test
        host: https://rinkeby.boba.network
        explorer: https://blockexplorer.rinkeby.boba.network/api
        multicall2: "0xeD188A73c442Df375b19b7b8f394a15a2b851BB5"
      - name: Mainnet
        chainid: 288
        id: boba-main
        host: https://mainnet.boba.network
        explorer: https://blockexplorer.boba.network/api
        multicall2: "0xbe2Be647F8aC42808E67431B4E1D6c19796bF586"
  - name: Fantom Opera
    networks:
      - name: Testnet
        chainid: 0xfa2
        id: ftm-test
        host: https://rpc.testnet.fantom.network
        explorer: https://explorer.testnet.fantom.network
      - name: Mainnet
        chainid: 250
        id: ftm-main
        host: https://rpc.ftm.tools
        explorer: https://api.ftmscan.com/api
  - name: Harmony
    networks:
      - name: Mainnet (Shard 0)
        chainid: 1666600000
        host: https://api.harmony.one
        id: harmony-main
        multicall2: "0x3E01dD8a5E1fb3481F0F589056b428Fc308AF0Fb"
  - name: Moonbeam
    networks:
      - name: Mainnet
        chainid: 1284
        id: moonbeam-main
        host: https://moonbeam.api.onfinality.io/public
        explorer: https://api-moonbeam.moonscan.io/api
        multicall2: "0x1337BedC9D22ecbe766dF105c9623922A27963EC"
      - name: Moonbase Alpha
        chainid: 1287 
        id: moonbeam-test
        host: https://moonbeam-alpha.api.onfinality.io/public
        explorer: https://api-moonbase.moonscan.io/api
        multicall2: "0x37084d0158C68128d6Bc3E5db537Be996f7B6979"
  - name: Moonriver
    networks:
      - name: Mainnet
        chainid: 1285
        id: moonriver-main
        host: https://moonriver.api.onfinality.io/public
        explorer: https://api-moonriver.moonscan.io/api
        multicall2: "0xaef00a0cf402d9dedd54092d9ca179be6f9e5ce3"
  - name: Optimistic Ethereum
    networks:
      - name: Mainnet
        chainid: 10
        id: optimism-main
        host: https://mainnet.optimism.io
        explorer: https://api-optimistic.etherscan.io/api
        multicall2: "0x2DC0E2aa608532Da689e89e237dF582B783E552C"
      - name: Kovan
        chainid: 69
        id: optimism-test
        host: https://kovan.optimism.io
        explorer: https://api-kovan-optimistic.etherscan.io/api
        multicall2: "0x2DC0E2aa608532Da689e89e237dF582B783E552C"
  - name: Polygon
    networks:
      - name: Mainnet (Infura)
        chainid: 137
        id: polygon-main
        host: https://polygon-mainnet.infura.io/v3/$WEB3_INFURA_PROJECT_ID
        explorer: https://api.polygonscan.com/api
        multicall2: "0xc8E51042792d7405184DfCa245F2d27B94D013b6"
      - name: Mumbai Testnet (Infura)
        chainid: 80001
        id: polygon-test
        host: https://polygon-mumbai.infura.io/v3/$WEB3_INFURA_PROJECT_ID
        explorer: https://api-testnet.polygonscan.com/api
        multicall2: "0x6842E0412AC1c00464dc48961330156a07268d14"
  - name: XDai
    networks:
      - name: Mainnet
        chainid: 100
        id: xdai-main
        host: https://xdai.poanetwork.dev
        explorer: https://blockscout.com/xdai/mainnet/api
      - name: Testnet
        chainid: 77
        id: xdai-test
        host: https://sokol.poa.network
        explorer: https://blockscout.com/poa/sokol/api

development:
  - name: Anvil
    id: anvil
    cmd: anvil
    host: http://127.0.0.1
    cmd_settings:
      port: 8545
  - name: Anvil (Mainnet Fork)
    id: anvil-fork
    cmd: anvil
    host: http://127.0.0.1
    cmd_settings:
      fork: mainnet
      port: 8545
  - name: Ganache-CLI
    id: development
    cmd: ganache-cli
    host: http://127.0.0.1
    cmd_settings:
      port: 8545
      gas_limit: 12000000
      accounts: 10
      evm_version: istanbul
      mnemonic: brownie
  - name: Geth Dev
    id: geth-dev
    cmd: ethnode
    host: http://127.0.0.1
    cmd_settings:
      port: 8545
  - name: Hardhat
    id: hardhat
    cmd: npx hardhat node
    host: http://localhost
    cmd_settings:
      port: 8545
  - name: Hardhat (Mainnet Fork)
    id: hardhat-fork
    cmd: npx hardhat node
    host: http://localhost
    timeout: 120
    cmd_settings:
      port: 8545
      fork: mainnet
  - name: Ganache-CLI (Mainnet Fork)
    id: mainnet-fork
    cmd: ganache-cli
    host: http://127.0.0.1
    timeout: 120
    cmd_settings:
      port: 8545
      gas_limit: 12000000
      accounts: 10
      evm_version: istanbul
      mnemonic: brownie
      fork: mainnet
  - name: Ganache-CLI (BSC-Mainnet Fork)
    id: bsc-main-fork
    cmd: ganache-cli
    host: http://127.0.0.1
    timeout: 120
    cmd_settings:
      port: 8545
      gas_limit: 12000000
      accounts: 10
      evm_version: istanbul
      mnemonic: brownie
      fork: bsc-main
  - name: Ganache-CLI (FTM-Mainnet Fork)
    id: ftm-main-fork
    cmd: ganache-cli
    host: http://127.0.0.1
    timeout: 120
    cmd_settings:
      port: 8545
      gas_limit: 12000000
      accounts: 10
      evm_version: istanbul
      mnemonic: brownie
      fork: ftm-main
  - name: Ganache-CLI (Polygon-Mainnet Fork)
    id: polygon-main-fork
    cmd: ganache-cli
    host: http://127.0.0.1
    timeout: 120
    cmd_settings:
      port: 8545
      gas_limit: 20000000
      accounts: 10
      evm_version: istanbul
      mnemonic: brownie
      fork: polygon-main
  - name: Ganache-CLI (XDai-Mainnet Fork)
    id: xdai-main-fork
    cmd: ganache-cli
    host: http://127.0.0.1
    timeout: 120
    cmd_settings:
      port: 8545
      gas_limit: 20000000
      accounts: 10
      evm_version: istanbul
      mnemonic: brownie
      fork: xdai-main
  - name: Ganache-CLI (Avax-Mainnet Fork)
    id: avax-main-fork
    cmd: ganache-cli
    host: http://127.0.0.1
    timeout: 120
    cmd_settings:
      port: 8545
      gas_limit: 20000000
      accounts: 10
      evm_version: istanbul
      mnemonic: brownie
      fork: avax-main
  - name: Ganache-CLI (Aurora-Mainnet Fork)
    id: aurora-main-fork
    cmd: ganache-cli
    host: http://127.0.0.1
    timeout: 120
    cmd_settings:
      port: 8545
      gas_limit: 20000000
      accounts: 10
      evm_version: istanbul
      mnemonic: brownie
      fork: aurora-main
``` 

Please update the network-config. yaml file deployed on Windows OS to the latest version.

Test environment:
- OS: Windows 11
- Python version: 3.11.1
- eth-brownie version: 1.19.3
